version: "3.9"
services:
  nginx_base:
    build:
      context: .
      dockerfile: Dockerfile.teste

  all_in_one_nginx:
    extends:
      service: nginx_base
    volumes:
      - "./all_in_one_nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
    ports:
      - "8001:8001"
      - "1935:1935"
      - "7045:7045"
      - "8002:8002"
      - "8003:8003"
      - "8004:8004"
      - "8005:8005"
    depends_on:
      - controller

  controller:
    build:
      context: .
      dockerfile: Dockerfile.controller
    ports:
      - "80:80"
    environment:
      - CC_DECODER_URL=kmp://127.0.0.1:8004
      - SEGMENTER_KMP_URL=kmp://127.0.0.1:8003
      - SEGMENTER_API_URL=http://all_in_one_nginx:8001/api/live
