version: "3.9"
services:
  nginx_base:
    build:
      context: .
      dockerfile: Dockerfile.kaltura-media-openresty

  allinonenginx:
    extends:
      service: nginx_base
    volumes:
      - "./all_in_one_nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
    ports:
      - "9090:9090" # External HTTP Server (packager)
      - "8001:8001" # Internal http server
      - "1935:1935" # RTMP
      - "7045:7045" # Haivision SRT
      - "8002:8002" # mpeg-ts
      - "8003:8003" # Segmenter (kmp input)
      - "8004:8004" # Closed caption decoder (kmp input)
      - "8005:8005" # RTMP output (kmp input)
    depends_on:
      - controller

  controller:
    build:
      context: .
      dockerfile: Dockerfile.controller
    ports:
      - "80:80"
    environment:
      - CC_DECODER_URL=kmp://127.0.0.1:8004
      - SEGMENTER_KMP_URL=kmp://127.0.0.1:8003
      - SEGMENTER_API_URL=http://allinonenginx:8001/api/live
